name: Rsync via NodeJS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Install rsync
      run: sudo apt-get --no-install-recommends install rsync
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Staging server
      run: npm run deploy --if-present
      env:
        CI: true,
        DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "dist"
        TARGET: ${{ secrets.SERVER_STAGING }}
