name: Rsync via NodeJS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Node version
      run: echo "##[set-output name=version;]$(node --version)"
      id: 'node_version'
    - name: Use Node.js 10.x
      if: contains(steps.node_version.outputs.version, '10.') == false
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to ${{ secrets.REMOTE_HOST }}
      run: |
        rsync ${ARGS}
        SSH_PATH="$HOME/.ssh"
        mkdir "$SSH_PATH"
        echo "${SSH_PRIVATE_KEY}" > "$SSH_PATH/deploy_key"
        chmod 600 "$SSH_PATH/deploy_key"
        rsync ${ARGS} -e 'ssh -i $SSH_PATH/deploy_key -o StrictHostKeyChecking=no' ${GITHUB_WORKSPACE}/${SOURCE} ${TARGET}"
      env:
        CI: true,
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "dist"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
