name: Rsync via NodeJS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check OS
      run: |
        node --version
        rsync --version
    - name: Check Node version
      run: echo "##[set-output name=version;]$(node --version)"
      id: 'node_version'
    - name: Use Node.js 10.x
      if: !contains(steps.node_version.outputs.version, '10.')
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install --ignore-scripts
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to ${{ secrets.REMOTE_HOST }}
      run: rsync -rltgoDzvO 
      env:
        CI: true,
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "dist"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
